// Patches the Android project generated by `cap add android` (CI only).
// Fails loudly if an expected pattern is missing, so a Capacitor template
// change never silently produces a wrong APK.
import fs from 'node:fs';
import path from 'node:path';

const run = process.env.GITHUB_RUN_NUMBER;
const expectedAppId = process.env.EXPECTED_APP_ID;

if (!run || !/^\d+$/.test(run)) throw new Error('GITHUB_RUN_NUMBER missing or not numeric');
if (!expectedAppId) throw new Error('EXPECTED_APP_ID missing');

const versionCode = Number(run);
const versionName = `0.0.${run}`;

function read(rel) {
  const p = path.join('android', rel);
  if (!fs.existsSync(p)) throw new Error(`Missing file: ${p}`);
  return { p, text: fs.readFileSync(p, 'utf8') };
}

// 1) app/build.gradle: versionCode / versionName / applicationId check
{
  const { p, text } = read('app/build.gradle');
  const vc = /versionCode\s*=?\s*\d+/;
  const vn = /versionName\s*=?\s*["'][^"']*["']/;
  if (!vc.test(text)) throw new Error('versionCode pattern not found in app/build.gradle');
  if (!vn.test(text)) throw new Error('versionName pattern not found in app/build.gradle');
  if (!text.includes(expectedAppId)) {
    throw new Error(`applicationId ${expectedAppId} not found in app/build.gradle`);
  }
  const out = text
    .replace(vc, `versionCode ${versionCode}`)
    .replace(vn, `versionName "${versionName}"`);
  fs.writeFileSync(p, out);
  console.log(`build.gradle: versionCode=${versionCode} versionName=${versionName}`);
}

// 2) AndroidManifest.xml: disable Android auto-backup
{
  const { p, text } = read('app/src/main/AndroidManifest.xml');
  let out = text;
  if (/android:allowBackup="[^"]*"/.test(out)) {
    out = out.replace(/android:allowBackup="[^"]*"/, 'android:allowBackup="false"');
  } else if (out.includes('<application')) {
    out = out.replace('<application', '<application android:allowBackup="false"');
  } else {
    throw new Error('<application> tag not found in AndroidManifest.xml');
  }
  if (!out.includes('android:allowBackup="false"')) {
    throw new Error('allowBackup patch failed');
  }
  fs.writeFileSync(p, out);
  console.log('AndroidManifest.xml: allowBackup=false');
}

console.log('Android patch OK');
